### ISSUE TITLE
Can I use this in laravel livewire?

### ISSUE THREAD

**Issue by jwhoami** [Laralabs/toaster#13]
How can I use this toaster in laravel livewire?
Can you provide some sample code
Thanks

**Comment by clnt** [comment]
Hi, this is a pretty old package built before anything like Livewire existed. It simply just puts the flashed session toast data in a JS object accessible to frontend libraries.

This package would probably achieve what you are after better: https://github.com/masmerise/livewire-toaster

Thanks
