### ISSUE TITLE
not working in laravel 10

### ISSUE THREAD

**Issue by LonelyDeev** [Laralabs/toaster#14]
hi
I installed the package on laravel 10 and called @toaster in the blade file in heade 
but it still doesn't work

**Comment by clnt** [comment]
Hi @LonelyBoy-dev ,

What are you using to display the toast message data on the frontend?

Calling `@toaster` in the blade file head will print out a JS variable with an object defining each toast message, if you inspect your source in browser - is this data present?

The demo site is running on Laravel 9 and there shouldn't be any breaking changes to this package with L10.

This is the Vue.js component I use on the demo site to display the data: https://github.com/Laralabs/vue-toaster which uses https://github.com/euvl/vue-notification
