### ISSUE TITLE
how can I trigger a toast message from vue?

### ISSUE THREAD

**Issue by prasanth223344** [Laralabs/toaster#7]
works great though, but I was expecting some api functions or some examples to call / change the messages from vue as well, would be much helpful on ajax / websocket calls.

**Comment by clnt** [comment]
Hi @prasanth223344 

Thanks for the feedback, I agree, I will look at updating the documentation to include this.

If using the Vue component, you can trigger a message from Vue by doing the following:

```
this.$notify({
  group: 'group-name',
  title: 'title',
  text: 'Message text',
  type: 'warn',
  duration: 3000,
  speed: 500
})
```

**Comment by prasanth223344** [comment]
thanks for your quick reply, yes, this works like a charm.

added to your tip I took hint from here 
https://www.npmjs.com/package/vue-notification
